# Generated by Django 3.1.4 on 2020-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100000000000)),
                ('short_link', models.CharField(max_length=1000000)),
            ],
        ),
    ]
